package priority

import "github.com/vpn-vendor/vpn-panel-core/internal/admission"

var Rules = []admission.Rule{

	{Method: "GET", Prefix: "/search", Class: admission.Sheddable},
	{Method: "GET", Prefix: "/qos/speedtest/status", Class: admission.Sheddable},
	{Method: "POST", Prefix: "/qos/speedtest", Class: admission.Sheddable},
	{Method: "GET", Prefix: "/diagnostics/probe/status", Class: admission.Sheddable},
	{Method: "POST", Prefix: "/diagnostics/probe", Class: admission.Sheddable},
	{Method: "POST", Prefix: "/diagnostics/support", Class: admission.Sheddable},
	{Method: "GET", Prefix: "/vpn/check/status", Class: admission.Sheddable},
	{Method: "POST", Prefix: "/vpn/check", Class: admission.Sheddable},
	{Method: "POST", Prefix: "/vpn/mtu", Class: admission.Sheddable},
	{Method: "GET", Prefix: "/lantest/data", Class: admission.Sheddable},
	{Method: "POST", Prefix: "/lantest/probe", Class: admission.Sheddable},
	{Method: "POST", Prefix: "/lantest/result", Class: admission.Sheddable},
	{Method: "GET", Prefix: "/network/suggest", Class: admission.Sheddable},
	{Method: "GET", Prefix: "/agent/ping", Class: admission.Sheddable},
	{Method: "GET", Prefix: "/metrics/series", Class: admission.Sheddable},

	{Prefix: "/", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/health", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/public", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/static", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/dns", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/help", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/qos", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/dhcp", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/devices", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/diagnostics", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/whoami", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/whoami", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/whoami/identify", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/lantest", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/vpn", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/vpn/import", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/vpn/timesync", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/security", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/network", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/network/confirming", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/backup", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/backup/import", Class: admission.Ordinary},
	{Method: "GET", Prefix: "/backup/confirming", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/backup/export/template", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/backup/export/copy", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/backup/import", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/backup/import/cards", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/backup/import/discard", Class: admission.Ordinary},
	{Method: "POST", Prefix: "/setup/speed", Class: admission.Ordinary},

	{Prefix: "/login", Class: admission.Critical},
	{Method: "GET", Prefix: "/setup", Class: admission.Critical},
	{Method: "POST", Prefix: "/setup", Class: admission.Critical},
	{Method: "POST", Prefix: "/qos/apply", Class: admission.Critical},
	{Method: "POST", Prefix: "/dhcp/reserve", Class: admission.Critical},
	{Method: "POST", Prefix: "/dhcp/unreserve", Class: admission.Critical},
	{Method: "POST", Prefix: "/devices/code", Class: admission.Critical},
	{Method: "POST", Prefix: "/devices/revoke", Class: admission.Critical},
	{Method: "POST", Prefix: "/devices/signout-others", Class: admission.Critical},
	{Method: "POST", Prefix: "/logout", Class: admission.Critical},
	{Method: "POST", Prefix: "/diagnostics/label", Class: admission.Critical},
	{Method: "POST", Prefix: "/diagnostics/proposal", Class: admission.Critical},
	{Method: "POST", Prefix: "/diagnostics/settings", Class: admission.Critical},
	{Method: "POST", Prefix: "/diagnostics/window", Class: admission.Critical},
	{Method: "POST", Prefix: "/diagnostics/identify", Class: admission.Critical},
	{Method: "POST", Prefix: "/diagnostics/fullcheck", Class: admission.Critical},
	{Method: "POST", Prefix: "/vpn/apply", Class: admission.Critical},
	{Method: "POST", Prefix: "/vpn/remove", Class: admission.Critical},
	{Method: "POST", Prefix: "/vpn/probe-target", Class: admission.Critical},
	{Method: "POST", Prefix: "/security", Class: admission.Critical},
	{Method: "POST", Prefix: "/network/apply", Class: admission.Critical},
	{Method: "POST", Prefix: "/network/confirm", Class: admission.Critical},
	{Method: "POST", Prefix: "/network/cancel", Class: admission.Critical},
	{Method: "POST", Prefix: "/backup/import/apply", Class: admission.Critical},
	{Method: "POST", Prefix: "/backup/confirm-network", Class: admission.Critical},
	{Method: "POST", Prefix: "/backup/confirm", Class: admission.Critical},
	{Method: "POST", Prefix: "/backup/rollback", Class: admission.Critical},
}
